---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/houses":
    get:
      summary: list houses
      responses:
        '200':
          description: successful
    post:
      summary: create house
      responses:
        '200':
          description: successful
  "/houses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show house
      responses:
        '200':
          description: successful
    delete:
      summary: delete house
      responses:
        '200':
          description: successful
  "/reservations/{username}":
    parameters:
    - name: username
      in: path
      description: username
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
  "/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost: 
      default: localhost
